positive_things_tracker/core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views
from .forms import LoginForm


app_name = "core"

urlpatterns = [
    path("", views.index, name="index"),
    path("contact/", views.contact, name="contact"),
    path("signup/", views.sign_up, name="signup"),
    path(
        "login/",
        auth_views.LoginView.as_view(
            template_name="core/login.html", authentication_form=LoginForm
        ),
        name="login",
    ),
]

positive_things_tracker/positive_things_tracker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls")),
]

positive_things_tracker/core/models.py
from django.db import models

# Create your models here.

positive_things_tracker/positive_thing/models.py
from django.db import models

# Create your models here.

positive_things_tracker/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class LoginForm(AuthenticationForm):
    email = forms.CharField(
        widget=forms.EmailInput(
            attrs={
                "placeholder": "Tu correo electrónico.",
                "class": "w-full px-6 py-4 rounded-xl ",
            }
        )
    )

    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Tu contraseña.",
                "class": "w-full px-6 py-4 rounded-xl ",
            }
        )
    )


class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "Tu nombre de usuario.",
                "class": "w-full px-6 py-4 rounded-xl ",
            }
        )
    )
    email = forms.CharField(
        widget=forms.EmailInput(
            attrs={
                "placeholder": "Tu correo electrónico.",
                "class": "w-full px-6 py-4 rounded-xl ",
            }
        )
    )
    password1 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Tu contraseña.",
                "class": "w-full px-6 py-4 rounded-xl ",
            }
        )
    )
    password2 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Tu contraseña.",
                "class": "w-full px-6 py-4 rounded-xl ",
            }
        )
    )

positive_things_tracker/core/views.py
from django.shortcuts import render, redirect

from .forms import SignUpForm


def index(request):
    return render(request, "core/index.html")


def contact(request):
    return render(request, "core/contact.html")


def sign_up(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect("/login/")
    else:
        form = SignUpForm()

    return render(request, "core/signup.html", {"form": form})

positive_things_tracker/positive_thing/views.py
from django.shortcuts import render

def index(request):
    return render(request, )

positive_things_tracker/core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <title>{% block title %} {% endblock %}| 5 Cosas Positivas</title>
</head>
<body>
    <nav class="px-6 py-6 flex justify-between items-center border-b border-gray-200">
        <a href="/" class="text-xl font-semibold"><b>5 Cosas Positivas</b></a>
        <div class="space-x-6">
            <a href="#" class="text-lg font-semibold hover:text-gray-500">Nuevas Cosas Positivas</a>

            {% if request.user.is_authenticated %}
                <a href="{% url 'core:index' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Mis Cosas Positivas</a>
            {% else %}
                <a href="{% url 'core:signup' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Registrarse</a>
                <a href="{% url 'core:login' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Iniciar Sesión</a>
            {% endif %}

        </div>
    </nav>
    <div class="px-6 py-6">
        {% block content %}
        {% endblock %}
    </div>

    <footer class="px-6 py-6 flex justify-between bg-gray-800">
        <div class="w-2/3 pr-10">
            <h3 class="mb-5 font-semibold text-gray-400">About</h3>

            <p class="text-lg text-gray-500">Lorem ipsum dolor, sit amet consectetur adipisicing elit. Accusantium, officia nisi nemo dicta et, voluptate cum, quidem nostrum architecto rerum error sit consequatur fugit officiis. Odit repellendus laboriosam dolore? Voluptate!</p>
        </div>
        <div class="w-1/3">
            <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>

            <ul class="space-y-2">
                <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">About</a></li>
                <li><a href="{% url 'core:contact' %}" class="text-lg text-teal-500 hover:text-teal-700">Contacto</a></li>
                <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Políticas de Privacidad</a></li>
                <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Términos de Uso</a></li>
            </ul>
        </div>
    </footer>
</body>
</html>

positive_things_tracker/core/templates/core/contact.html
{% extends 'core/base.html' %}
{% block title %}Contact {% endblock %} 

{% block content %}
    <h1>The Contact Page.</h1>
{% endblock %}

positive_things_tracker/core/templates/core/index.html
{% extends 'core/base.html' %}
{% block title %}Bienvenido {% endblock %} 

{% block content %}
    <div class="mt-6 px-6 py-6 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Bienvenido</h2>
    </div>
{% endblock %}

positive_things_tracker/core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}Iniciar Sesión {% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Iniciar Sesión</h1>

    <form method="post" action=".">
        {% csrf_token %}
        
        <div class="mb-3">
            <label class="inline-block mb-2">Correo Electrónico</label><br>
            {{ form.email }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Contraseña</label><br>
            {{ form.password }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors}}
                {% endfor %}
                
                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button class="px-8 py-4 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Aceptar</button>
    </form>
</div>
{% endblock %}

positive_things_tracker/core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %}Registrarse {% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Registrarse</h1>

    <form method="post" action=".">
        {% csrf_token %}
        
        <div class="mb-3">
            <label class="inline-block mb-2">Nombre de Usuario</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Correo Electrónico</label><br>
            {{ form.email }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Contraseña</label><br>
            {{ form.password1 }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Repita la Contraseña</label><br>
            {{ form.password2 }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors}}
                {% endfor %}
                
                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button class="px-8 py-4 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Aceptar</button>
    </form>
</div>
{% endblock %}